# Generated by Django 5.2 on 2025-04-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
