# Generated by Django 5.2 on 2025-04-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notefile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'subject')},
        ),
    ]
