# Generated by Django 5.2 on 2025-04-18 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notesolvesolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesolverequest',
            name='requested_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='solve_requests_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
