# Generated by Django 5.2 on 2025-04-18 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notesolverequest_requested_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesolverequest',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notesolve_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
