# Generated by Django 5.2 on 2025-04-18 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notesolverequest_requested_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesolvesolution',
            name='solve_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='core.notesolverequest'),
        ),
    ]
