# Generated by Django 5.2 on 2025-04-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notesolvesolution_solve_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesolvesolution',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notesolvesolution',
            name='solution_text',
            field=models.TextField(blank=True),
        ),
    ]
