# Generated by Django 5.2.17 on 2026-10-01 06:36

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_premiumpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('basic', 'Basic User'), ('provider', 'Provider'), ('moderator', 'Moderator')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='notes/', validators=[core.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='notefile',
            name='file',
            field=models.FileField(upload_to='notes/', validators=[core.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='notesolvefile',
            name='file',
            field=models.FileField(upload_to='notesolve_files/', validators=[core.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='notesolvesolution',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='note_solve_solutions/', validators=[core.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='duration_in_months',
            field=models.IntegerField(),
        ),
    ]
