# Generated by Django 5.2.17 on 2026-10-01 06:36

from django.db import migrations


def admin_to_moderator(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    CustomUser.objects.filter(user_type='admin').update(user_type='moderator')


def moderator_to_admin(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    CustomUser.objects.filter(user_type='moderator').update(user_type='admin')


class Migration(migrations.Migration):
    """The old 'admin' user type becomes the new 'moderator' role."""

    dependencies = [
        ('core', '0015_roles_and_upload_validation'),
    ]

    operations = [
        migrations.RunPython(admin_to_moderator, moderator_to_admin),
    ]
