# Generated by Django 5.2.17 on 2026-10-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_friendships_to_follows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
