# Generated by Django 5.2.17 on 2026-10-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_existing_users_email_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_note', 'New note from a provider you follow'), ('new_follower', 'New follower'), ('note_rejected', 'Your note was not approved')], max_length=20),
        ),
    ]
