# Generated by Django 5.2.17 on 2026-10-01 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_note_rejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Use a semester from 1 to 12.'), django.core.validators.MaxValueValidator(12, 'Use a semester from 1 to 12.')]),
        ),
        migrations.AlterField(
            model_name='note',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Use a year of study from 1 to 5.'), django.core.validators.MaxValueValidator(5, 'Use a year of study from 1 to 5.')]),
        ),
        migrations.AlterField(
            model_name='notesolverequest',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Use a year of study from 1 to 5.'), django.core.validators.MaxValueValidator(5, 'Use a year of study from 1 to 5.')]),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='duration_in_months',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Use 1 to 36 months.'), django.core.validators.MaxValueValidator(36, 'Use 1 to 36 months.')]),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1, 'The price must be at least 1 taka.')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Use a semester from 1 to 12.'), django.core.validators.MaxValueValidator(12, 'Use a semester from 1 to 12.')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Use a year of study from 1 to 5.'), django.core.validators.MaxValueValidator(5, 'Use a year of study from 1 to 5.')]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Use a semester from 1 to 12.'), django.core.validators.MaxValueValidator(12, 'Use a semester from 1 to 12.')]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Use a year of study from 1 to 5.'), django.core.validators.MaxValueValidator(5, 'Use a year of study from 1 to 5.')]),
        ),
    ]
