# Generated by Django 5.2.17 on 2026-10-03 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_orders_to_packages(apps, schema_editor):
    """Existing orders only stored the package name; link the ones whose package still exists."""
    PremiumPackage = apps.get_model('core', 'PremiumPackage')
    PremiumPurchase = apps.get_model('core', 'PremiumPurchase')
    for package in PremiumPackage.objects.all():
        PremiumPurchase.objects.filter(package__isnull=True, package_name=package.name).update(package=package)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_premium_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.premiumpurchase'),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='on sale'),
        ),
        migrations.AddField(
            model_name='premiumpurchase',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.premiumpackage'),
        ),
        migrations.AddField(
            model_name='premiumpurchase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_note', 'New note from a provider you follow'), ('new_follower', 'New follower'), ('note_rejected', 'Your note was not approved'), ('premium_approved', 'Your Premium order was approved'), ('premium_rejected', 'Your Premium order was not approved'), ('premium_ending', 'Your Premium ends soon'), ('premium_ended', 'Your Premium has ended'), ('premium_order', 'New Premium order to review')], max_length=20),
        ),
        migrations.RunPython(link_orders_to_packages, migrations.RunPython.noop),
    ]
